# Use the official OpenSearch image as the base image
FROM opensearchproject/opensearch:1.2.0 as build


# Health check (optional)
HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
  CMD curl -f http://localhost:9200 || exit 1

# Run as non-root user (optional, but recommended for security)
USER opensearch

# Define the entry point
ENTRYPOINT ["/usr/share/opensearch/bin/opensearch"]
