FROM opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2

# Copy the Logstash configuration file into the container
COPY config/logstash.conf /usr/share/logstash/pipeline/logstash.conf

# Expose the necessary ports
EXPOSE 5044

# Run Logstash
CMD ["-f", "/usr/share/logstash/pipeline/logstash.conf"]
