version: '3.7'

networks:
  opensearch-net:
    driver: bridge

volumes:
  opensearch-data:
    driver: local

services:
  logstash:
      build:
        context: .
        dockerfile: Dockerfile.logstash
      networks:
        - opensearch-net
      ports:
      - "5044:5044"
      environment:
        - XPACK_SECURITY_HTTP_SSL_ENABLED=false
        - XPACK_SECURITY_HTTP_SSL_VERIFICATION_MODE=none
        - xpack.security.http.ssl.enabled=false
        - xpack.security.http.ssl.verification_mode=none
        - XPACK_MONITORING_ENABLED=false
        - xpack.monitoring.elasticsearch.ssl.verification_mode=none
        - ssl_verification_mode=none
      depends_on:
        - opensearch
        
  filebeat:
    build:
      context: .
      dockerfile: Dockerfile.filebeat
    depends_on:
      - logstash
      - opensearch
    networks:
      - opensearch-net
  
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      #  plugins.security.disabled=true
      - plugins.security.ssl.http.enabled=false
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=GoCoronaGo#2020
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      # - OPENSEARCH_USERNAME=kibanaserver
      # - OPENSEARCH_PASSWORD=GoCoronaGo@2020

    networks:
      - opensearch-net
    depends_on:
      - opensearch