filebeat.inputs:
  - type: filestream
    id: my-filestream-id
    enabled: true
    paths:
      - /Users/pawansankhle/Documents/workspace/logs/cortex.log
# — — — — — — — — — — Logstash output — — — — — — — — — —
output.logstash:
  hosts: ["logstash:5045"]
